# Generated by Django 3.1.2 on 2020-10-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201014_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_root', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=10)),
                ('student_sex', models.CharField(max_length=2)),
                ('student_id', models.IntegerField()),
            ],
        ),
    ]
